name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: windows
      TARGET: msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-msvc-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-msvc-

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install extra tools
        run: choco install ccache ninja wget

      - name: Disable line ending translation
        run: git config --global core.autocrlf input

      - name: Build
        run: ./.ci/windows.sh

      - name: Pack
        run: ./.ci/pack.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc
          path: artifacts/
